# NumPy Arrays

In [1]:
my_list = [1, 2, 3]

In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<b> np.arange() method returns evenly spaced values within a given interval </b>

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0, 11, 2)              # from 0(inclusive) to 11(exclusive) in steps of 2

array([ 0,  2,  4,  6,  8, 10])

<b> np.zeros() returns a vector/matrice in which all the elements are 0 </b>

In [10]:
np.zeros(3)                     # returns a 1D vector with 3 elements all of which are zero

array([ 0.,  0.,  0.])

In [11]:
np.zeros((5,5))                # returns a 5 X 5 matrix, each element is 0

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [12]:
# returns a 2 X 3 matrix
np.zeros((2,3))        

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

<b> np.ones() returns a vector/matrice in which all the elements are 1 </b>

In [13]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [14]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

<b> np.linspace() returns evenly spaced numbers over a specified interval </b>

In [15]:
np.linspace(0, 5, 10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [16]:
np.linspace(0, 5, 100)

array([ 0.        ,  0.05050505,  0.1010101 ,  0.15151515,  0.2020202 ,
        0.25252525,  0.3030303 ,  0.35353535,  0.4040404 ,  0.45454545,
        0.50505051,  0.55555556,  0.60606061,  0.65656566,  0.70707071,
        0.75757576,  0.80808081,  0.85858586,  0.90909091,  0.95959596,
        1.01010101,  1.06060606,  1.11111111,  1.16161616,  1.21212121,
        1.26262626,  1.31313131,  1.36363636,  1.41414141,  1.46464646,
        1.51515152,  1.56565657,  1.61616162,  1.66666667,  1.71717172,
        1.76767677,  1.81818182,  1.86868687,  1.91919192,  1.96969697,
        2.02020202,  2.07070707,  2.12121212,  2.17171717,  2.22222222,
        2.27272727,  2.32323232,  2.37373737,  2.42424242,  2.47474747,
        2.52525253,  2.57575758,  2.62626263,  2.67676768,  2.72727273,
        2.77777778,  2.82828283,  2.87878788,  2.92929293,  2.97979798,
        3.03030303,  3.08080808,  3.13131313,  3.18181818,  3.23232323,
        3.28282828,  3.33333333,  3.38383838,  3.43434343,  3.48

<b> <code> np.eye() </code> returns an identity matrix(diagonal elements are 1 and all other elements are 0) </b>

In [17]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [20]:
np.eye(4,6)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.]])

<b> <code> numpy.random.rand() </code> Create an array of the given shape and populate it with the random samples from a uniform distribution over [0, 1) </b>

In [18]:
np.random.rand(5)

array([ 0.01606288,  0.61533734,  0.6762102 ,  0.63489559,  0.61449773])

In [19]:
np.random.rand(4, 5)

array([[ 0.8222209 ,  0.25285971,  0.47358719,  0.85336562,  0.94435891],
       [ 0.34524417,  0.22467977,  0.75114151,  0.83873161,  0.05733743],
       [ 0.40332329,  0.64388027,  0.63751434,  0.9438544 ,  0.25011517],
       [ 0.64091184,  0.6011279 ,  0.04192863,  0.36178832,  0.68323199]])

<b> <code> numpy.random.randn() </code> Create an array of the given shape and populate it with the random samples from a standard normal distribution </b>

In [21]:
np.random.randn(2)

array([-0.51753487, -0.91838546])

In [22]:
np.random.randn(4, 4)

array([[ 1.09649429, -0.90561631, -0.18635601,  0.28705094],
       [ 0.20722645,  0.26503005, -0.50063255, -0.57620362],
       [-0.27289593,  1.13391725, -0.30585464, -0.44478529],
       [-1.8367097 ,  0.53262742, -0.86965045,  0.2761967 ]])

<b> <code> numpy.random.randint(low, high = None, size = None) </code> Return random integers from `low`(inclusive) to `high`(exclusive) </b>

In [23]:
np.random.randint(1, 100)

14

In [24]:
# returns 10 random integers in the range 1 to 100(exclusive)

np.random.randint(1, 100, 10)

array([30, 93, 21, 98, 97, 95, 14, 29, 88, 72])

In [25]:
arr = np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0, 50, 10)

In [28]:
ranarr

array([ 7,  1, 44,  7, 17,  5, 22, 42, 23, 16])

In [29]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
arr.reshape(5, 10)        # this would give an error as we only have 25 elements in arr

ValueError: cannot reshape array of size 25 into shape (5,10)

In [31]:
ranarr.max()

44

In [32]:
ranarr.min()

1

In [33]:
ranarr

array([ 7,  1, 44,  7, 17,  5, 22, 42, 23, 16])

In [34]:
ranarr.argmax()             # returns the index of maximum element

2

In [35]:
ranarr.argmin()         # returns index of minium element

1

In [36]:
arr.shape

(25,)

In [37]:
arr.dtype

dtype('int32')

# NumPy Indexing and Selection

In [38]:
arr = np.arange(0, 11)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr[8]              # gives element at 8th index

8

In [41]:
arr[1:5]           # gives elements with index in range 1(inclusive) to 5(exclusive)

array([1, 2, 3, 4])

In [42]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [43]:
arr[:6]             # all elements till index 6

array([0, 1, 2, 3, 4, 5])

In [44]:
arr[5:]            # all elements starting from index 5

array([ 5,  6,  7,  8,  9, 10])

In [45]:
arr[0:5] = 100               # change first 5 elements to 100

In [46]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [47]:
arr = np.arange(0, 11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
slice_of_arr = arr[0:6]

In [50]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [51]:
slice_of_arr[:] = 99

In [52]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [53]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Since slice_of_arr refers to first 6 elements of arr, when we change slice_of_arr then the elements of arr are also changed

<br>

To make a copy of an array in numpy,we need to use the copy() function

In [54]:
arr_copy = arr.copy()

In [55]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
arr_copy[:] = 100

In [58]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [59]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
arr_2d = np.array([[5, 10, 15], [15, 20, 25], [30, 35, 40]])

In [61]:
arr_2d

array([[ 5, 10, 15],
       [15, 20, 25],
       [30, 35, 40]])

In [62]:
arr_2d[0]                      # returns first row

array([ 5, 10, 15])

In [63]:
arr_2d[1][1]                  # returns element at first row and first column

20

In [64]:
arr_2d[1, 2]                  # 1st row and 2nd col -> 25  

25

In [65]:
arr_2d[:2, 1:]                # first 2 rows and last 2 columns

array([[10, 15],
       [20, 25]])

In [66]:
arr_2d[:2]

array([[ 5, 10, 15],
       [15, 20, 25]])

<h4> Conditional Operator </h4>

In [67]:
arr = np.arange(0, 11)

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

In [70]:
bool_arr = arr > 5

In [71]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

In [72]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [73]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [74]:
arr[arr < 3]

array([0, 1, 2])

In [75]:
arr_2d = np.arange(50).reshape(5, 10)

In [76]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [77]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [78]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

<h4> NumPy Operations </h4>

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [81]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [82]:
arr = np.arange(0, 11)

In [83]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [85]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [86]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [87]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [88]:
1 / 0

ZeroDivisionError: division by zero

In [89]:
arr / arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

<b> 0 / 0 gives nan in numpy </b>

In [90]:
1 / arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

<b> 1 / 0 gives infinity in numpy </b>

In [91]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [92]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [93]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [94]:
np.max(arr)

10

In [95]:
arr.max()

10

In [96]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [97]:
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])